<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-8QJ5818" name="testNG.Keyword" tests="12" failures="0" timestamp="2 Dec 2020 10:10:20 GMT" time="5.142" errors="2">
  <testcase name="TC1" time="0.012" classname="testNG.Keyword"/>
  <testcase name="TC1" time="0.006" classname="testNG.Keyword"/>
  <testcase name="TC1" time="0.012" classname="testNG.Keyword"/>
  <testcase name="TC1" time="0.008" classname="testNG.Keyword"/>
  <testcase name="TC1" time="0.008" classname="testNG.Keyword"/>
  <testcase name="TC1" time="0.009" classname="testNG.Keyword"/>
  <testcase name="TC1" time="0.008" classname="testNG.Keyword"/>
  <testcase name="TC1" time="0.009" classname="testNG.Keyword"/>
  <testcase name="Login" time="5.027" classname="testNG.Keyword">
    <error type="org.testng.internal.thread.ThreadTimeoutException" message="Method org.testng.internal.TestNGMethod.Login() didn&#039;t finish within the time-out 5000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method org.testng.internal.TestNGMethod.Login() didn't finish within the time-out 5000
	at java.util.concurrent.ThreadPoolExecutor.processWorkerExit(ThreadPoolExecutor.java:1002)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </error>
  </testcase> <!-- Login -->
  <testcase name="TC1" time="0.038" classname="testNG.Keyword"/>
  <testcase name="TC1" time="0.005" classname="testNG.Keyword"/>
  <testcase name="TC2" time="0.000" classname="testNG.Keyword">
    <error type="java.lang.Throwable" message="Method Keyword.TC2()[pri:0, instance:testNG.Keyword@2b98378d] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method Keyword.TC2()[pri:0, instance:testNG.Keyword@2b98378d] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1028)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
    </error>
  </testcase> <!-- TC2 -->
</testsuite> <!-- testNG.Keyword -->
